# --------------- Stack Variables --------------- #
# Don't use Uppercase or special character
Stack_Name: api-wedding
# -------------- Tags Variables -------------- #
Tag_App: api-wedding
Tag_Project: MandMwedding
# --------------- DynamoDB Settings --------------- #
DynamoDB_Table: api-wedding-list
Read_Units: 1
Write_Units: 1
# ------------ Domain Options ------------ #
customDomain:
  domainName: apiwed.mrzablah.com
  certificateName: mrzablah.com
  stage: ${self:provider.stage}
  securityPolicy: tls_1_2
# ------------ Optional Variables ------------ #
Region: us-east-1
Stage: prod
Timeout: 5
MemorySize: 128
LogRetention: 5